'use client';
import { useState, useEffect, useRef } from 'react';
const LAUNCH = new Date(Date.now()+30*24*3600000+17*3600000);
const SVCS = ['Plumbing','Electrical','HVAC','Landscaping','Painting','Carpentry','Cleaning','Moving','Web Development','Graphic Design','Writing','Marketing','Photography','Other'];
function useCD(t) { const [n,sN]=useState(Date.now()); useEffect(()=>{const i=setInterval(()=>sN(Date.now()),1000);return()=>clearInterval(i)},[]);const d=Math.max(0,t.getTime()-n);return{d:Math.floor(d/864e5),h:Math.floor(d%864e5/36e5),m:Math.floor(d%36e5/6e4),s:Math.floor(d%6e4/1e3)}; }
export default function WaitlistPage(){const cd=useCD(LAUNCH);const[un,sU]=useState('');const[em,sE]=useState('');const[rl,sR]=useState('');const[sv,sV]=useState([]);const[sub,sS]=useState(false);const[rc,sRC]=useState('');const[sr,sSR]=useState(false);const[si,sSI]=useState(false);const[idea,sId]=useState('');const[us,sUS]=useState('idle');const tr=useRef(null);
const chk=(v)=>{sU(v);sUS('idle');if(tr.current)clearTimeout(tr.current);if(v.length>=3){sUS('checking');tr.current=setTimeout(()=>sUS(v.toLowerCase()==='admin'?'taken':'available'),800);}};
const togS=(s)=>sV(p=>p.includes(s)?p.filter(x=>x!==s):[...p,s]);
const sub2=(e)=>{e.preventDefault();if(!un||!em||!rl)return;sS(true);sRC(`VTL-${un.toUpperCase().slice(0,4)}-${Math.random().toString(36).slice(2,6).toUpperCase()}`);};
const cdB=(v,l)=>(<div style={{textAlign:'center',minWidth:80}}><div style={{fontSize:48,fontWeight:900,fontFamily:'var(--font-display)',color:'var(--gold-2)',lineHeight:1,textShadow:'0 0 30px rgba(201,168,76,0.3)'}}>{String(v).padStart(2,'0')}</div><div style={{fontSize:10,color:'var(--muted)',fontFamily:'var(--font-mono)',letterSpacing:'0.2em',marginTop:4,textTransform:'uppercase'}}>{l}</div></div>);
return(<div style={{minHeight:'100vh',background:'linear-gradient(180deg,#010a20 0%,#020f2e 40%,#071435 100%)',color:'var(--white)',padding:0}}>
<div style={{background:'linear-gradient(90deg,rgba(201,168,76,0.08),transparent,rgba(201,168,76,0.08))',borderBottom:'1px solid rgba(201,168,76,0.15)',padding:'16px 24px',textAlign:'center'}}><div style={{fontFamily:'var(--font-display)',fontSize:22,color:'var(--gold)',letterSpacing:'0.15em'}}>VERITAS NETWORK</div><div style={{fontSize:11,color:'var(--muted)',fontFamily:'var(--font-mono)',letterSpacing:'0.2em',marginTop:4}}>TRUTH BECOMES TRUST</div></div>
<div style={{maxWidth:640,margin:'0 auto',padding:'40px 20px'}}>
<div style={{textAlign:'center',marginBottom:40}}><h1 style={{fontFamily:'var(--font-display)',fontSize:28,marginBottom:8}}>Launch Countdown</h1><p style={{color:'var(--muted)',fontSize:13,marginBottom:24}}>Claim your username before anyone else.</p><div style={{display:'flex',justifyContent:'center',gap:16,flexWrap:'wrap'}}>{cdB(cd.d,'Days')}{cdB(cd.h,'Hours')}{cdB(cd.m,'Minutes')}{cdB(cd.s,'Seconds')}</div></div>
{!sub?(<form onSubmit={sub2}>
<div className="card-gold" style={{marginBottom:20,padding:'1.5rem'}}><div className="card-title" style={{fontSize:16}}>Choose Your Username</div><p style={{fontSize:12,color:'var(--muted)',marginBottom:12}}>Your username is permanent on Veritas. It appears on your TruScore, badges, and every partner platform.</p><div style={{position:'relative'}}><input className="v-input" value={un} onChange={e=>chk(e.target.value.replace(/[^a-zA-Z0-9_]/g,''))} placeholder="e.g. ProPlumber_Mike" style={{paddingRight:40}} />{us==='checking'&&<span style={{position:'absolute',right:12,top:'50%',transform:'translateY(-50%)',fontSize:14}}>⏳</span>}{us==='available'&&<span style={{position:'absolute',right:12,top:'50%',transform:'translateY(-50%)',color:'var(--success)',fontSize:14}}>✅</span>}{us==='taken'&&<span style={{position:'absolute',right:12,top:'50%',transform:'translateY(-50%)',color:'var(--danger)',fontSize:14}}>❌</span>}</div></div>
<div style={{marginBottom:20}}><label className="v-label">Email</label><input className="v-input" type="email" value={em} onChange={e=>sE(e.target.value)} placeholder="you@example.com" required /></div>
<div style={{marginBottom:20}}><label className="v-label">I am a...</label><div style={{display:'flex',gap:12}}><button type="button" onClick={()=>sR('worker')} style={{flex:1,padding:16,borderRadius:12,border:'2px solid '+(rl==='worker'?'var(--gold)':'var(--border-2)'),background:rl==='worker'?'rgba(201,168,76,0.08)':'transparent',cursor:'pointer',textAlign:'center'}}><div style={{fontSize:28,marginBottom:4}}>🔧</div><div style={{fontSize:14,fontWeight:700,color:rl==='worker'?'var(--gold)':'var(--white)'}}>Gig Worker</div></button><button type="button" onClick={()=>sR('client')} style={{flex:1,padding:16,borderRadius:12,border:'2px solid '+(rl==='client'?'var(--cyan)':'var(--border-2)'),background:rl==='client'?'rgba(6,182,212,0.08)':'transparent',cursor:'pointer',textAlign:'center'}}><div style={{fontSize:28,marginBottom:4}}>💼</div><div style={{fontSize:14,fontWeight:700,color:rl==='client'?'var(--cyan)':'var(--white)'}}>Customer</div></button></div></div>
{rl&&<div style={{marginBottom:20}}><label className="v-label">{rl==='worker'?'Services You Offer':'Services You Need'}</label><div style={{display:'flex',flexWrap:'wrap',gap:6}}>{SVCS.map(s=><button key={s} type="button" onClick={()=>togS(s)} style={{fontSize:11,padding:'5px 12px',borderRadius:999,border:'1px solid '+(sv.includes(s)?'var(--gold)':'var(--border-2)'),background:sv.includes(s)?'rgba(201,168,76,0.1)':'transparent',color:sv.includes(s)?'var(--gold)':'var(--muted)',cursor:'pointer'}}>{s}</button>)}</div></div>}
<button className="btn btn-gold" type="submit" style={{width:'100%',padding:'16px 0',fontSize:16,fontWeight:800}}>Join the Waitlist →</button>
</form>):(<div className="card-gold" style={{textAlign:'center',padding:'2rem'}}><div style={{fontSize:48,marginBottom:12}}>🎉</div><h2 style={{fontFamily:'var(--font-display)',fontSize:22,color:'var(--gold)',marginBottom:8}}>Welcome, @{un}!</h2><p style={{color:'var(--muted)',fontSize:13,marginBottom:16}}>Your username is reserved.</p><div className="serial-display" style={{marginBottom:8}}><div style={{fontSize:10,color:'var(--muted)',marginBottom:4}}>REFERRAL CODE</div><div className="serial-value" style={{fontSize:18}}>{rc}</div></div></div>)}
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:24}}>
<a href="mailto:founder@veritasledger.com" className="card" style={{textAlign:'center',padding:'16px 12px',textDecoration:'none'}}><div style={{fontSize:24,marginBottom:6}}>✉️</div><div style={{fontSize:13,fontWeight:600,color:'var(--white)'}}>Email Us</div></a>
<a href="/" className="card" style={{textAlign:'center',padding:'16px 12px',textDecoration:'none'}}><div style={{fontSize:24,marginBottom:6}}>🌐</div><div style={{fontSize:13,fontWeight:600,color:'var(--white)'}}>View Site</div></a>
<button onClick={()=>sSI(!si)} className="card" style={{textAlign:'center',padding:'16px 12px',cursor:'pointer',border:'1px solid var(--border-2)',background:'linear-gradient(135deg,#071435,#051a4a)'}}><div style={{fontSize:24,marginBottom:6}}>💡</div><div style={{fontSize:13,fontWeight:600,color:'var(--white)'}}>Add Ideas</div></button>
<button onClick={()=>sSR(!sr)} className="card" style={{textAlign:'center',padding:'16px 12px',cursor:'pointer',border:'1px solid var(--border-gold)',background:'linear-gradient(135deg,#071435,#0a1933)'}}><div style={{fontSize:24,marginBottom:6}}>🔗</div><div style={{fontSize:13,fontWeight:600,color:'var(--gold)'}}>Referral Rules</div></button>
</div>
{sr&&<div className="card-gold" style={{marginTop:16,padding:'1.25rem'}}><div className="card-title">Referral Rules</div><div style={{fontSize:13,color:'var(--muted)',lineHeight:1.7}}><p>1. Share your code with friends.</p><p>2. Both earn priority placement.</p><p>3. 5+ referrals = Gold Founding Badge.</p><p>4. 20+ = Diamond Founding Badge.</p><p>5. Founding Members get early access + reduced fees.</p></div></div>}
</div></div>);}