'use client';
import { useEffect, useState } from 'react';
import { useAuth } from '../layout';
function NS({ icon, label, value, sub, glow }) { return (<div style={{ background:'linear-gradient(135deg,rgba(7,20,53,0.9),rgba(5,26,74,0.7))', border:'1px solid rgba(6,182,212,0.15)', borderRadius:14, padding:'16px 18px', flex:1, minWidth:155, position:'relative', overflow:'hidden' }}>{glow && <div style={{ position:'absolute', top:-20, right:-20, width:60, height:60, borderRadius:'50%', background:glow, opacity:0.15, filter:'blur(20px)' }} />}<div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:10 }}><span style={{ fontSize:18 }}>{icon}</span><span style={{ fontSize:10, fontFamily:'var(--font-mono)', color:'var(--muted)', letterSpacing:'0.12em', textTransform:'uppercase' }}>{label}</span></div><div style={{ fontSize:26, fontWeight:900, fontFamily:'var(--font-mono)', color:'var(--white)', lineHeight:1 }}>{value}</div>{sub && <div style={{ fontSize:10, color:'var(--muted)', marginTop:6 }}>{sub}</div>}</div>); }
function TC({ data }) { const max = Math.max(...data, 100), h = 150, w = 480; const pts = data.map((v, i) => `${(i/(data.length-1))*w},${h-(v/max)*h}`).join(' '); return (<div style={{ overflowX:'auto' }}><svg width={w} height={h+24} style={{ display:'block', minWidth:w }}><defs><linearGradient id="cg" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#06b6d4" stopOpacity="0.25" /><stop offset="100%" stopColor="#06b6d4" stopOpacity="0" /></linearGradient></defs>{[0,0.25,0.5,0.75,1].map(f => <line key={f} x1={0} y1={h*f} x2={w} y2={h*f} stroke="rgba(255,255,255,0.04)" strokeWidth="1" />)}<polygon points={`0,${h} ${pts} ${w},${h}`} fill="url(#cg)" /><polyline points={pts} fill="none" stroke="#06b6d4" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />{data.map((v,i) => <circle key={i} cx={(i/(data.length-1))*w} cy={h-(v/max)*h} r="3.5" fill="#06b6d4" stroke="#020f2e" strokeWidth="2" />)}{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].slice(0,data.length).map((l,i) => <text key={i} x={(i/(data.length-1))*w} y={h+16} textAnchor="middle" fill="rgba(255,255,255,0.25)" fontSize="9" fontFamily="monospace">{l}</text>)}</svg></div>); }
function Badge({ name, icon, earned }) { return (<div style={{ textAlign:'center', padding:'12px 8px', borderRadius:12, minWidth:80, background: earned?'linear-gradient(135deg,rgba(201,168,76,0.1),rgba(201,168,76,0.03))':'rgba(255,255,255,0.02)', border:`1px solid ${earned?'rgba(201,168,76,0.25)':'rgba(255,255,255,0.05)'}`, opacity: earned?1:0.4 }}><div style={{ fontSize:28, marginBottom:4 }}>{icon}</div><div style={{ fontSize:9, fontFamily:'var(--font-mono)', color: earned?'var(--gold)':'var(--muted)', letterSpacing:'0.05em' }}>{name}</div></div>); }
const TI = { Starter:{color:'#94a3b8',glow:'rgba(148,163,184,0.2)',next:'Bronze',max:200}, Bronze:{color:'#cd7f32',glow:'rgba(205,127,50,0.2)',next:'Silver',max:400}, Silver:{color:'#c0c0c0',glow:'rgba(192,192,192,0.2)',next:'Gold',max:600}, Gold:{color:'#ffd700',glow:'rgba(255,215,0,0.2)',next:'Platinum',max:800}, Platinum:{color:'#e5e4e2',glow:'rgba(229,228,226,0.3)',next:'Diamond',max:950}, Diamond:{color:'#b9f2ff',glow:'rgba(185,242,255,0.3)',next:'Max',max:1000} };
export default function DashboardPage() {
  const { user } = useAuth(); const p = user || {}; const score = Number(p.truScore||p.truscore||0); const tier = p.tier||'Starter'; const tc = TI[tier]||TI.Starter;
  const [clock, setClock] = useState(''); useEffect(() => { const t = setInterval(() => setClock(new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit'})), 1000); return () => clearInterval(t); }, []);
  const chartData = [40,120,180,250,310,380,420,490,560,640,720,score||100]; const jobsDone = p.jobs_completed||0; const earned = p.total_earned||0;
  return (<div style={{ maxWidth:1200 }} className="animate-fade-up">
    <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:24, flexWrap:'wrap', gap:16 }}>
      <div><h2 style={{ fontFamily:'var(--font-display)', fontSize:26, marginBottom:4 }}>Welcome Back, <span style={{ color:'var(--gold-2)' }}>{p.name||'User'}</span></h2><p style={{ color:'var(--muted)', fontSize:12, fontFamily:'var(--font-mono)' }}>{p.role==='admin'?'Administrator':p.role==='worker'?'Verified Freelancer':'Client'} · {clock||'—'}</p></div>
      <div style={{ width:56, height:56, borderRadius:'50%', background: p.avatar_url?'none':`linear-gradient(135deg,${tc.color},var(--navy-3))`, display:'flex', alignItems:'center', justifyContent:'center', fontSize:22, fontWeight:800, color:'var(--navy)', border:`2px solid ${tc.color}`, boxShadow:`0 0 20px ${tc.glow}`, overflow:'hidden' }}>{p.avatar_url ? <img src={p.avatar_url} alt="" style={{ width:'100%', height:'100%', objectFit:'cover' }} /> : (p.name?.charAt(0)?.toUpperCase()||'U')}</div>
    </div>
    <div style={{ background:'linear-gradient(135deg,rgba(7,20,53,0.95),rgba(5,26,74,0.8))', border:'1px solid rgba(201,168,76,0.2)', borderRadius:18, padding:'24px 28px', marginBottom:24, position:'relative', overflow:'hidden' }}>
      <div style={{ position:'absolute', top:-40, right:-40, width:200, height:200, borderRadius:'50%', background:tc.glow, opacity:0.2, filter:'blur(60px)' }} />
      <div style={{ display:'flex', alignItems:'center', gap:24, flexWrap:'wrap', position:'relative', zIndex:1 }}>
        <div style={{ textAlign:'center', minWidth:140 }}><div style={{ fontSize:10, fontFamily:'var(--font-mono)', color:'var(--muted)', letterSpacing:'0.15em', marginBottom:4 }}>VERITAS TRU-SCORE</div><div style={{ fontSize:64, fontWeight:900, fontFamily:'var(--font-mono)', color:'var(--gold-2)', lineHeight:1, textShadow:`0 0 40px ${tc.glow}` }}>{score}</div><div style={{ display:'inline-block', marginTop:8, padding:'4px 16px', borderRadius:999, background:`${tc.color}22`, border:`1px solid ${tc.color}44`, color:tc.color, fontSize:11, fontFamily:'var(--font-mono)', fontWeight:700, letterSpacing:'0.1em' }}>{tier.toUpperCase()}</div></div>
        <div style={{ flex:1, minWidth:200 }}><div style={{ display:'flex', gap:20, flexWrap:'wrap', marginBottom:12 }}><div><div style={{ fontSize:10, color:'var(--muted)', fontFamily:'var(--font-mono)' }}>NEXT TIER</div><div style={{ fontSize:14, fontWeight:600 }}>{tc.next} ({tc.max})</div></div><div><div style={{ fontSize:10, color:'var(--muted)', fontFamily:'var(--font-mono)' }}>SERIAL</div><div style={{ fontSize:14, fontWeight:600, color:'var(--cyan-2)', fontFamily:'var(--font-mono)' }}>{p.serial||'—'}</div></div></div><div style={{ height:8, background:'rgba(255,255,255,0.05)', borderRadius:4, overflow:'hidden', marginBottom:8 }}><div style={{ height:'100%', width:Math.min(score/tc.max*100,100)+'%', background:`linear-gradient(90deg,${tc.color},var(--cyan))`, borderRadius:4, transition:'width 1s ease', boxShadow:`0 0 12px ${tc.glow}` }} /></div><div style={{ display:'flex', gap:24, flexWrap:'wrap' }}><div style={{ fontSize:12, color:'var(--muted)' }}>🏗 <strong style={{ color:'var(--white)' }}>{jobsDone}</strong> Jobs</div><div style={{ fontSize:12, color:'var(--muted)' }}>💰 <strong style={{ color:'var(--white)' }}>${Number(earned).toLocaleString()}</strong> Volume</div></div></div>
      </div>
    </div>
    <div style={{ display:'flex', gap:14, marginBottom:24, flexWrap:'wrap' }}><NS icon="💼" label="Role" value={String(p.role||'worker').toUpperCase()} glow="rgba(6,182,212,0.3)" /><NS icon="🛡" label="Tier" value={tier} sub={`Next: ${tc.next}`} glow={tc.glow} /><NS icon="✉️" label="Verified" value={p.emailVerified||p.is_verified?'Yes':'Pending'} glow={p.emailVerified?'rgba(34,197,94,0.3)':'rgba(239,68,68,0.2)'} /><NS icon="⭐" label="Rating" value={p.avg_rating?Number(p.avg_rating).toFixed(1):'—'} sub="Avg rating" glow="rgba(251,191,36,0.2)" /></div>
    <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))', gap:20, marginBottom:24 }}>
      <div style={{ background:'linear-gradient(135deg,rgba(7,20,53,0.9),rgba(5,26,74,0.7))', border:'1px solid rgba(6,182,212,0.12)', borderRadius:16, padding:20 }}><div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:16 }}><div className="card-title" style={{ margin:0 }}>📈 Trust Ledger</div></div><TC data={chartData} /></div>
      <div style={{ background:'linear-gradient(135deg,rgba(7,20,53,0.9),rgba(5,26,74,0.7))', border:'1px solid rgba(255,255,255,0.06)', borderRadius:16, padding:20 }}><div className="card-title" style={{ marginBottom:16 }}>🔗 Latest Transactions</div>{[{t:'Proofreading',a:'$148',s:'completed',ti:'2h ago'},{t:'Web Development',a:'$2,400',s:'in escrow',ti:'5h ago'},{t:'Graphic Design',a:'$680',s:'completed',ti:'1d ago'},{t:'HVAC Repair',a:'$350',s:'released',ti:'2d ago'}].map((tx,i) => (<div key={i} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'10px 0', borderBottom: i<3?'1px solid var(--border)':'none' }}><div><div style={{ fontSize:13, fontWeight:500 }}>{tx.t}</div><div style={{ fontSize:10, color:'var(--muted)' }}>{tx.ti}</div></div><div style={{ textAlign:'right' }}><div style={{ fontSize:14, fontWeight:700, fontFamily:'var(--font-mono)', color:'var(--gold-2)' }}>{tx.a}</div><span style={{ fontSize:9, fontFamily:'var(--font-mono)', padding:'2px 8px', borderRadius:999, background: tx.s==='completed'?'rgba(34,197,94,0.12)':tx.s==='in escrow'?'rgba(6,182,212,0.1)':'rgba(201,168,76,0.1)', border:`1px solid ${tx.s==='completed'?'rgba(34,197,94,0.3)':tx.s==='in escrow'?'rgba(6,182,212,0.3)':'rgba(201,168,76,0.3)'}`, color: tx.s==='completed'?'#22c55e':tx.s==='in escrow'?'var(--cyan)':'var(--gold)' }}>{tx.s}</span></div></div>))}</div>
    </div>
    <div style={{ background:'linear-gradient(135deg,rgba(7,20,53,0.9),rgba(5,26,74,0.7))', border:'1px solid rgba(201,168,76,0.15)', borderRadius:16, padding:20, marginBottom:24 }}><div className="card-title" style={{ marginBottom:16 }}>🏆 Achievements</div><div style={{ display:'flex', gap:12, flexWrap:'wrap' }}><Badge name="New Member" icon="🔰" earned={true} /><Badge name="10 Jobs" icon="⭐" earned={jobsDone>=10} /><Badge name="50 Jobs" icon="🥇" earned={jobsDone>=50} /><Badge name="100 Jobs" icon="🏆" earned={jobsDone>=100} /><Badge name="1st Escrow" icon="🔒" earned={true} /><Badge name="Escrow Master" icon="💎" earned={false} /><Badge name="Top Score" icon="👑" earned={score>=900} /><Badge name="1 Year" icon="📅" earned={false} /></div></div>
  </div>);
}
