'use client';
import { useAuth } from '../layout';
const H=[{date:'Apr 26',event:'Job Completed: Web Development',change:'+45',score:720},{date:'Apr 24',event:'Escrow Released: $2,400',change:'+30',score:675},{date:'Apr 22',event:'Peer Review: 5/5 Stars',change:'+15',score:645},{date:'Apr 20',event:'Identity Verified',change:'+50',score:630},{date:'Apr 18',event:'Job Completed: Logo Design',change:'+35',score:580},{date:'Apr 15',event:'Dispute Resolved (Favorable)',change:'+10',score:545},{date:'Apr 12',event:'Escrow Released: $680',change:'+25',score:535},{date:'Apr 10',event:'Account Created',change:'+100',score:510}];
const F=[{name:'Transaction Success',weight:25,score:92,color:'#22c55e'},{name:'Peer Reviews',weight:20,score:88,color:'#06b6d4'},{name:'Identity Verification',weight:15,score:100,color:'#ffd700'},{name:'Escrow Completion',weight:15,score:95,color:'#a78bfa'},{name:'Dispute History',weight:10,score:90,color:'#f59e0b'},{name:'Network Trust',weight:10,score:78,color:'#ec4899'},{name:'Ledger Integrity',weight:5,score:100,color:'#34d399'}];
export default function TrustPage(){const{user}=useAuth();const score=Number(user?.truScore||user?.truscore||0);const tier=user?.tier||'Starter';
return(<div style={{maxWidth:1200}} className="animate-fade-up"><div style={{marginBottom:24}}><h2 style={{fontFamily:'var(--font-display)',fontSize:24,marginBottom:4}}>Trust Ledger</h2><p style={{color:'var(--muted)',fontSize:12}}>Your complete reputation history</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:20,marginBottom:24}}>
<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.95),rgba(5,26,74,0.8))',border:'1px solid rgba(201,168,76,0.2)',borderRadius:16,padding:24}}><div style={{fontSize:14,fontFamily:'var(--font-display)',color:'var(--gold)',marginBottom:20}}>Score Breakdown</div><div style={{textAlign:'center',marginBottom:20}}><div style={{fontSize:56,fontWeight:900,fontFamily:'var(--font-mono)',color:'var(--gold-2)'}}>{score}</div><div style={{fontSize:12,color:'var(--muted)',fontFamily:'var(--font-mono)'}}>{tier.toUpperCase()} · out of 1000</div></div>{F.map((f,i)=><div key={i} style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',fontSize:11,marginBottom:4}}><span style={{color:'var(--muted)'}}>{f.name} ({f.weight}%)</span><span style={{color:f.color,fontFamily:'var(--font-mono)'}}>{f.score}%</span></div><div style={{height:5,background:'rgba(255,255,255,0.05)',borderRadius:3,overflow:'hidden'}}><div style={{height:'100%',width:f.score+'%',background:f.color,borderRadius:3}}/></div></div>)}</div>
<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.9),rgba(5,26,74,0.7))',border:'1px solid rgba(6,182,212,0.12)',borderRadius:16,padding:24}}><div style={{fontSize:14,fontFamily:'var(--font-display)',color:'var(--gold)',marginBottom:20}}>Ledger History</div>{H.map((h,i)=><div key={i} style={{display:'flex',gap:12,padding:'10px 0',borderBottom:i<H.length-1?'1px solid var(--border)':'none',alignItems:'center'}}><div style={{width:6,height:6,borderRadius:'50%',background:h.change.startsWith('+')?'#22c55e':'#ef4444',flexShrink:0}}/><div style={{flex:1}}><div style={{fontSize:12,fontWeight:500}}>{h.event}</div><div style={{fontSize:10,color:'var(--muted)'}}>{h.date}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:13,fontWeight:700,fontFamily:'var(--font-mono)',color:h.change.startsWith('+')?'#22c55e':'#ef4444'}}>{h.change}</div><div style={{fontSize:10,color:'var(--muted)',fontFamily:'var(--font-mono)'}}>→ {h.score}</div></div></div>)}</div>
</div>
<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.9),rgba(5,26,74,0.7))',border:'1px solid rgba(255,255,255,0.06)',borderRadius:16,padding:20}}><div style={{fontSize:14,fontFamily:'var(--font-display)',color:'var(--gold)',marginBottom:12}}>Ledger Integrity</div><p style={{fontSize:12,color:'var(--muted)',lineHeight:1.8}}>Every event is cryptographically sealed using SHA-256 hash chaining. If any record is altered, the chain breaks — making fraud mathematically impossible.</p><div style={{marginTop:12,display:'flex',gap:16,flexWrap:'wrap',fontSize:11,color:'var(--muted)'}}><span>🔗 Chain: <strong style={{color:'var(--cyan)'}}>{H.length} events</strong></span><span>✅ Integrity: <strong style={{color:'#22c55e'}}>100%</strong></span><span>🛡 Encryption: <strong style={{color:'var(--gold)'}}>AES-256 + ES512</strong></span></div></div></div>);}
