'use client';
import { useEffect, useState } from 'react';
import { useAuth } from '../layout';
function M({label,value,icon,color,trend,sub}){return(<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.95),rgba(5,26,74,0.8))',border:'1px solid rgba(6,182,212,0.12)',borderRadius:14,padding:'16px 18px',flex:1,minWidth:170,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',top:-15,right:-15,width:50,height:50,borderRadius:'50%',background:color,opacity:0.2,filter:'blur(15px)'}}/><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:10}}><span style={{fontSize:16}}>{icon}</span><span style={{fontSize:9,fontFamily:'var(--font-mono)',color:'var(--muted)',letterSpacing:'0.12em',textTransform:'uppercase'}}>{label}</span></div><div style={{fontSize:28,fontWeight:900,fontFamily:'var(--font-mono)',color:'var(--white)',lineHeight:1}}>{value}</div><div style={{display:'flex',alignItems:'center',gap:6,marginTop:6}}>{trend!==undefined&&<span style={{fontSize:10,color:trend>=0?'#22c55e':'#ef4444',fontFamily:'var(--font-mono)'}}>{trend>=0?'↑':'↓'}{Math.abs(trend)}%</span>}{sub&&<span style={{fontSize:10,color:'var(--muted)'}}>{sub}</span>}</div></div>);}
export default function AdminPage(){const{user}=useAuth();const[clock,setClock]=useState('');useEffect(()=>{const t=setInterval(()=>setClock(new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit'})),1000);return()=>clearInterval(t);},[]);
if(user?.role!=='admin')return(<div style={{maxWidth:600,textAlign:'center',padding:'80px 20px'}}><div style={{fontSize:48,marginBottom:16}}>🔒</div><h2 style={{fontFamily:'var(--font-display)',fontSize:22,marginBottom:8}}>Admin Access Required</h2></div>);
return(<div style={{maxWidth:1300}} className="animate-fade-up"><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:28,flexWrap:'wrap',gap:16}}><div><h2 style={{fontFamily:'var(--font-display)',fontSize:26,marginBottom:4}}>Welcome Back, <span style={{color:'var(--gold-2)'}}>{user?.name||'Admin'}</span></h2><p style={{color:'var(--muted)',fontSize:12,fontFamily:'var(--font-mono)'}}>Administrator · {clock}</p></div><div className="live-pill"><div className="live-dot"/>SYSTEM ONLINE</div></div>
<div style={{display:'flex',gap:14,marginBottom:20,flexWrap:'wrap'}}><M icon="👥" label="Total Users" value="43,207" trend={4.3} sub="this month" color="rgba(6,182,212,0.3)"/><M icon="💰" label="Escrow Volume" value="$5.3M" trend={12.8} sub="all time" color="rgba(201,168,76,0.3)"/><M icon="⚖️" label="Disputes" value="12" sub="77 resolved" color="rgba(239,68,68,0.2)"/><M icon="✅" label="Reliability" value="99.5%" trend={0.2} color="rgba(34,197,94,0.3)"/></div>
<div style={{display:'flex',gap:14,marginBottom:24,flexWrap:'wrap'}}><M icon="🔧" label="Workers" value="28,340" sub="+187 today" color="rgba(6,182,212,0.2)"/><M icon="💼" label="Clients" value="14,867" color="rgba(201,168,76,0.2)"/><M icon="📋" label="Jobs" value="58,420" sub="3,210 open" color="rgba(6,182,212,0.2)"/><M icon="🏆" label="Badges" value="127,500" color="rgba(255,215,0,0.2)"/><M icon="📝" label="Waitlist" value="12,840" trend={8.1} color="rgba(185,242,255,0.2)"/></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:20,marginBottom:24}}>
<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.95),rgba(5,26,74,0.8))',border:'1px solid rgba(6,182,212,0.12)',borderRadius:16,padding:20}}><div className="card-title" style={{marginBottom:16}}>🔒 Security Audit</div><div style={{fontSize:42,fontWeight:900,fontFamily:'var(--font-mono)',color:'#22c55e',marginBottom:4}}>99.9%</div><div style={{fontSize:11,color:'var(--muted)',marginBottom:16}}>Detection Accuracy</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div style={{background:'rgba(239,68,68,0.05)',border:'1px solid rgba(239,68,68,0.15)',borderRadius:10,padding:12}}><div style={{fontSize:9,fontFamily:'var(--font-mono)',color:'var(--muted)',marginBottom:4}}>FRAUD FLAGS</div><div style={{fontSize:22,fontWeight:800,fontFamily:'var(--font-mono)',color:'#ef4444'}}>3</div></div><div style={{background:'rgba(251,191,36,0.05)',border:'1px solid rgba(251,191,36,0.15)',borderRadius:10,padding:12}}><div style={{fontSize:9,fontFamily:'var(--font-mono)',color:'var(--muted)',marginBottom:4}}>SUSPICIOUS</div><div style={{fontSize:22,fontWeight:800,fontFamily:'var(--font-mono)',color:'#fbbf24'}}>8</div></div></div></div>
<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.95),rgba(5,26,74,0.8))',border:'1px solid rgba(255,255,255,0.06)',borderRadius:16,padding:20}}><div className="card-title" style={{marginBottom:16}}>🔔 Activity</div><div style={{maxHeight:280,overflowY:'auto'}}>{[{t:'New user: @ElectricMike',ti:'2m ago',tp:'user'},{t:'Escrow #8842 funded — $1,200',ti:'5m ago',tp:'escrow'},{t:'Job posted: Kitchen Remodel',ti:'8m ago',tp:'job'},{t:'Badge: @ProPlumber → Gold',ti:'12m ago',tp:'badge'},{t:'Dispute #D-0089 resolved',ti:'18m ago',tp:'dispute'},{t:'TruScore: 847 users recalculated',ti:'30m ago',tp:'system'}].map((a,i)=><div key={i} style={{display:'flex',gap:10,padding:'8px 0',borderBottom:'1px solid var(--border)'}}><span style={{fontSize:14}}>{{user:'👤',escrow:'🔒',job:'💼',badge:'🏆',dispute:'⚖️',system:'⚙️'}[a.tp]}</span><div><div style={{fontSize:12,lineHeight:1.5}}>{a.t}</div><div style={{fontSize:9,color:'var(--muted)',fontFamily:'var(--font-mono)'}}>{a.ti}</div></div></div>)}</div></div>
</div>
<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.95),rgba(5,26,74,0.8))',border:'1px solid rgba(201,168,76,0.12)',borderRadius:16,padding:20}}><div className="card-title" style={{marginBottom:16}}>💰 Escrow Overview</div><div style={{display:'flex',gap:14,flexWrap:'wrap'}}>{[{l:'Active',v:'1,531',c:'var(--cyan)'},{l:'Released',v:'42,180',c:'#22c55e'},{l:'Disputed',v:'89',c:'#ef4444'},{l:'Volume',v:'$5.28M',c:'var(--gold)'},{l:'Fee Revenue',v:'$132K',c:'var(--gold-2)'}].map((e,i)=><div key={i} style={{flex:1,minWidth:130,background:'rgba(255,255,255,0.02)',border:'1px solid var(--border)',borderRadius:10,padding:'12px 14px',textAlign:'center'}}><div style={{fontSize:9,fontFamily:'var(--font-mono)',color:'var(--muted)',letterSpacing:'0.1em',marginBottom:4}}>{e.l.toUpperCase()}</div><div style={{fontSize:22,fontWeight:800,fontFamily:'var(--font-mono)',color:e.c}}>{e.v}</div></div>)}</div></div></div>);}
