function basicServiceTemplate(data) {

  return `
VERITAS SERVICE AGREEMENT

----------------------------------------

PROJECT TITLE:
${data.title}

----------------------------------------

CLIENT:
${data.client_name}

WORKER:
${data.worker_name}

----------------------------------------

DESCRIPTION:

${data.description}

----------------------------------------

TOTAL CONTRACT VALUE:
$${data.total_amount}

----------------------------------------

MILESTONES:

${data.milestones.map((m, i) => `
${i + 1}. ${m.title}
Amount: $${m.amount}
`).join("\n")}

----------------------------------------

DISPUTES:

Both parties agree that disputes will first
be reviewed through the Veritas Trust
Ledger dispute resolution system.

----------------------------------------

MATERIALS:

Any approved materials purchased for this
job must include receipts uploaded into
the Veritas platform.

----------------------------------------

ESCROW:

Funds remain in escrow until milestone
approval or dispute resolution.

----------------------------------------

SIGNATURES:

Client Signature: ___________________

Worker Signature: ___________________

----------------------------------------

Generated by Veritas Trust Ledger
`;
}

module.exports = basicServiceTemplate;