'use client';
import { useState } from 'react';
import { useAuth } from "@/context/AuthContext";
const CATS=['All','Plumbing','Electrical','HVAC','Landscaping','Painting','Carpentry','Cleaning','Moving','Web Development','Graphic Design','Writing','Marketing','Photography','Other'];
const JOBS=[{id:'j1',title:'Kitchen Sink Repair',cat:'Plumbing',budget:280,client:'Sarah M.',tier:'Gold',score:720,posted:'2h ago',apps:4,desc:'Licensed plumber needed for kitchen sink replacement.'},{id:'j2',title:'Full Stack Web App',cat:'Web Development',budget:4500,client:'Tech Corp',tier:'Platinum',score:890,posted:'5h ago',apps:12,desc:'React + Node.js inventory management app. 6-week timeline.'},{id:'j3',title:'Logo & Brand Identity',cat:'Graphic Design',budget:800,client:'Alex K.',tier:'Silver',score:480,posted:'1d ago',apps:8,desc:'Complete brand identity for new restaurant.'},{id:'j4',title:'Lawn Maintenance',cat:'Landscaping',budget:200,client:'HomeOwner LLC',tier:'Gold',score:650,posted:'1d ago',apps:3,desc:'Weekly lawn maintenance for commercial property.'},{id:'j5',title:'Blog Content Writing',cat:'Writing',budget:150,client:'Diana W.',tier:'Bronze',score:320,posted:'2d ago',apps:6,desc:'5 SEO blog posts per month.'},{id:'j6',title:'Electrical Panel Upgrade',cat:'Electrical',budget:1200,client:'Mark T.',tier:'Diamond',score:940,posted:'3h ago',apps:2,desc:'200-amp panel upgrade. Licensed electrician required.'}];
export default function JobsPage(){const{user}=useAuth();const[cat,setCat]=useState('All');const[search,setSearch]=useState('');const[showPost,setShowPost]=useState(false);const filtered=JOBS.filter(j=>(cat==='All'||j.cat===cat)&&(!search||j.title.toLowerCase().includes(search.toLowerCase())));const tc=(t)=>({Starter:'#94a3b8',Bronze:'#cd7f32',Silver:'#c0c0c0',Gold:'#ffd700',Platinum:'#e5e4e2',Diamond:'#b9f2ff'}[t]||'#94a3b8');
return(<div style={{maxWidth:1200}} className="animate-fade-up"><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:24,flexWrap:'wrap',gap:12}}><div><h2 style={{fontFamily:'var(--font-display)',fontSize:24,marginBottom:4}}>Job Marketplace</h2><p style={{color:'var(--muted)',fontSize:12}}>Find verified gig work or post a job</p></div><button className="btn btn-gold" onClick={()=>setShowPost(!showPost)}>{showPost?'✕ Cancel':'+ Post a Job'}</button></div>
{showPost&&<div style={{background:'linear-gradient(135deg,rgba(7,20,53,0.95),rgba(5,26,74,0.8))',border:'1px solid rgba(201,168,76,0.2)',borderRadius:16,padding:24,marginBottom:24}}><div style={{fontSize:14,fontFamily:'var(--font-display)',color:'var(--gold)',marginBottom:16}}>Post a New Job</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginBottom:14}}><div><label className="v-label">Job Title</label><input className="v-input" placeholder="e.g. Kitchen Sink Repair"/></div><div><label className="v-label">Budget ($)</label><input className="v-input" type="number" placeholder="500"/></div></div><div style={{marginBottom:14}}><label className="v-label">Description</label><textarea className="v-input" rows={3} placeholder="Describe the job..." style={{resize:'vertical'}}/></div><button className="btn btn-gold" style={{width:'100%',padding:'12px 0'}}>Post Job →</button></div>}
<div style={{marginBottom:20}}><input className="v-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search jobs..." style={{marginBottom:12,maxWidth:400}}/><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{CATS.map(c=><button key={c} onClick={()=>setCat(c)} style={{fontSize:11,padding:'5px 14px',borderRadius:999,border:'1px solid '+(cat===c?'var(--cyan)':'var(--border-2)'),background:cat===c?'rgba(6,182,212,0.1)':'transparent',color:cat===c?'var(--cyan)':'var(--muted)',cursor:'pointer',fontFamily:'var(--font-mono)'}}>{c}</button>)}</div></div>
<div style={{display:'grid',gap:16}}>{filtered.map(j=><div key={j.id} style={{background:'linear-gradient(135deg,rgba(7,20,53,0.9),rgba(5,26,74,0.7))',border:'1px solid rgba(6,182,212,0.1)',borderRadius:16,padding:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap',gap:12}}><div style={{flex:1,minWidth:250}}><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:6}}><span style={{fontSize:15,fontWeight:600}}>{j.title}</span><span style={{fontSize:9,padding:'2px 8px',borderRadius:999,background:'rgba(6,182,212,0.1)',border:'1px solid rgba(6,182,212,0.2)',color:'var(--cyan)',fontFamily:'var(--font-mono)'}}>{j.cat}</span></div><p style={{fontSize:12,color:'var(--muted)',lineHeight:1.6,marginBottom:10}}>{j.desc}</p><div style={{display:'flex',gap:16,fontSize:11,color:'var(--muted)',flexWrap:'wrap'}}><span>👤 {j.client}</span><span style={{color:tc(j.tier)}}>🛡 {j.tier} ({j.score})</span><span>📝 {j.apps} apps</span><span>🕐 {j.posted}</span></div></div><div style={{textAlign:'right',minWidth:120}}><div style={{fontSize:24,fontWeight:900,fontFamily:'var(--font-mono)',color:'var(--gold-2)',marginBottom:8}}>${j.budget.toLocaleString()}</div><button className="btn btn-cyan" style={{fontSize:12,padding:'8px 20px'}}>Apply →</button></div></div></div>)}</div></div>);}
